name: AWS CloudFront Invalidate Action
description: Create an invalidation for a CloudFront distribution.

branding:
  icon: refresh-cw
  color: purple

inputs:
  id:
    description: The ID of the distribution
    required: false
  domain-name:
    description: Alternative domain name (CNAME) associated with the CloudFront distribution
    required: false
  paths:
    description: |
      The paths to be invalidated.
      You can specify multiple paths by separating them with a newline.
    required: false
    default: "/*"
  caller-reference:
    description: A value that you specify to uniquely identify an invalidation request.
    required: false
  wait:
    description: Wait for the invalidation to complete
    required: false
    default: "true"

outputs:
  invalidation-id:
    description: The ID of the invalidation
runs:
  using: node20
  main: dist/index.js
